### ISSUE TITLE
Cannot access https://update.openchrom.net/repositories/community/latest/jre with type p2 using the available connector factories

### ISSUE THREAD

**Issue by suhande** [OpenChrom/openchrom#165]
when i run maven build, i got this error, how can i fix it? 
```
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.eclipse.chemclipse:master:pom:0.9.0-SNAPSHOT from/to jre-packaging (https://update.openchrom.net/repositories/community/latest/jre): Cannot access https://update.openchrom.net/repositories/community/latest/jre with type p2 using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
	... 29 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access https://update.openchrom.net/repositories/community/latest/jre with type p2 using the available connector factories: AetherRepositoryConnectorFactory, BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:167)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:511)
	... 30 more
```

**Comment by Mailaender** [comment]
I fail to reproduce this locally. Note that https://update.openchrom.net/ is a server located in Europe with not so great connectivity to Asia. I also suspect it could be a firewall related problem.
